#!/usr/bin/env bash
# =============================================================================
# setup_ansible.sh  ─  Load .env and run ansible-playbook
# Usage: bash setup_ansible.sh [extra ansible-playbook options]
# e.g.:  bash setup_ansible.sh --check --diff  # dry-run
#        bash setup_ansible.sh --limit target  # specific host only
# =============================================================================

set -euo pipefail

ENV_FILE=".env"

# ── Load .env ─────────────────────────────────────────────────────────────
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "❌  ${ENV_FILE} not found. Run 'make setup' first."
  exit 1
fi

echo "📄  Loading ${ENV_FILE}..."
# Export variables, skipping comments and blank lines
set -a
# shellcheck disable=SC1090
source <(grep -v '^\s*#' "${ENV_FILE}" | grep -v '^\s*$')
set +a

# ── Required variable check ────────────────────────────────────────────────
required_vars=(HOST USER CF_TUNNEL_TOKEN SUDO_PASS)
for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "❌  ${var} is not set in ${ENV_FILE}."
    exit 1
  fi
done

if [[ "${ENABLE_TUNNEL:-false}" == "true" ]]; then
  for var in SUBDOMAIN DOMAIN; do
    if [[ -z "${!var:-}" ]]; then
      echo "❌  ${var} is not set in ${ENV_FILE} (required when ENABLE_TUNNEL=true)."
      exit 1
    fi
  done
fi

# ── Generate ansible/inventory/hosts.ini ──────────────────────────────────
INVENTORY_FILE="ansible/inventory/hosts.ini"

if [[ "${ENABLE_TUNNEL:-false}" == "true" ]]; then
  SSH_CFG="ansible/.tunnel_ssh.cfg"
  TUNNEL_HOST="${SUBDOMAIN}.${DOMAIN}"
  cat > "${SSH_CFG}" <<EOF
Host ${TUNNEL_HOST}
    ProxyCommand cloudflared access ssh --hostname ${TUNNEL_HOST}
    ${KEY:+IdentityFile ${KEY}}
    StrictHostKeyChecking accept-new
EOF
  SSH_COMMON_ARGS="ansible_ssh_common_args='-F ${SSH_CFG}'"
  INV_HOST="${TUNNEL_HOST}"
  INV_PORT=""
else
  SSH_COMMON_ARGS=""
  INV_HOST="${HOST}"
  INV_PORT="ansible_port=${PORT:-22}"
fi

cat > "${INVENTORY_FILE}" <<EOF
# Auto-generated by setup_ansible.sh from .env — do not edit directly

[servers]
target ansible_host=${INV_HOST} ansible_user=${USER} ${INV_PORT} ${KEY:+ansible_ssh_private_key_file=${KEY}} ${SSH_COMMON_ARGS}
EOF

echo "✅  hosts.ini generated (host: ${HOST}, user: ${USER}, tunnel: ${ENABLE_TUNNEL:-false})"

# ── Run ansible-playbook ───────────────────────────────────────────────────
# Prompt for confirmation when --check is not given (i.e. live apply)
if [[ ! " $* " =~ " --check " ]]; then
  echo ""
  echo "⚠️  This will apply ansible-playbook to ${HOST}."
  read -rp "Continue? [y/N]: " CONFIRM
  case "${CONFIRM}" in
    [yY]*) ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

# ── Cloudflare Access login (tunnel mode only) ────────────────────────────
if [[ "${ENABLE_TUNNEL:-false}" == "true" ]]; then
  echo "🔐  Authenticating with Cloudflare Access (${TUNNEL_HOST})..."
  cloudflared access login "${TUNNEL_HOST}"
fi

ansible-playbook \
  -i ansible/inventory/hosts.ini \
  ansible/site.yaml \
  -e "cf_tunnel_token=${CF_TUNNEL_TOKEN}" \
  -e "ansible_become_pass=${SUDO_PASS}" \
  "$@"
